environment=DEV

logging.level.root=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=ERROR
logging.level.com.bridgelabz=DEBUG

<<<<<<< HEAD
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%line] %nSg%n
=======
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%line] %n

>>>>>>> 4f277df88f6325dc8f6f30aac98858da15dfc55d
